Repository ezsystems/repository-forms, pull requests merged in 2018-04, with the labels that each got.

#231 EZP-28224: Use PHP5.6 compatible function
  lib/Form/Processor/ContentTypeFormProcessor.php
Labels: ready for review

#232 EZP-28224: Fix Behat tests
  .travis.yml
  features/Context/PagelayoutContext.php
  features/Context/UserRegistrationContext.php
  features/User/Registration/user_registration.feature
Labels: ready for review

#221 EZP-28551: [Media and Binary] You can set maximum file size to less than zero
  bundle/Resources/config/form_types.yml
  bundle/Resources/config/services.yml
  lib/ConfigResolver/MaxUploadSize.php
  lib/FieldType/Mapper/BinaryFileFormMapper.php
  lib/FieldType/Mapper/ImageFormMapper.php
  lib/FieldType/Mapper/MediaFormMapper.php
  lib/Form/Type/FieldType/BinaryBaseFieldType.php
Labels: QA done, bug

#235 EZP-28224: Fix Behat in 2.0
  composer.json
  features/Context/ContentEdit.php
  features/Context/FieldTypeFormContext.php
  features/Context/UserRegistrationContext.php
  features/FieldTypeForm/checkbox_fieldtype_edit_form.feature
  features/FieldTypeForm/selection_fieldtype_edit_form.feature
  features/FieldTypeForm/textline_fieldtype_edit_form.feature
  features/FieldTypeForm/user_fieldtype_edit_form.feature
  features/User/Registration/user_registration.feature
Labels: Ready to merge

#236 EZP-29024: Adding policy user/register to the role throws 500
  bundle/EzSystemsRepositoryFormsBundle.php
  lib/Security/UserRegisterPolicyProvider.php
Labels: QA done, ready for review
