Repository ezsystems/repository-forms, pull requests merged in 2018-03, with the labels that each got.

#214 EZP-28850: Add optional location parameter to draft edit for more appropriate redirection
  bundle/Controller/ContentEditController.php
  bundle/Resources/config/routing.yml
  lib/Form/ActionDispatcher/ContentDispatcher.php
  lib/Form/Processor/ContentFormProcessor.php
Labels: enhancement

#215 EZP-28849: Allow repository forms to use View Manager for handling draft edit controller and template dispatching
  bundle/Controller/ContentEditController.php
  bundle/DependencyInjection/Compiler/ViewBuilderRegistryPass.php
  bundle/DependencyInjection/Configuration/Parser/ContentEditView.php
  bundle/EzSystemsRepositoryFormsBundle.php
  bundle/Resources/config/ezpublish_default_settings.yml
  bundle/Resources/config/routing.yml
  bundle/Resources/config/services.yml
  bundle/Resources/config/views.yml
  lib/Content/View/Builder/ContentEditViewBuilder.php
  lib/Content/View/ContentEditView.php
  lib/Content/View/Filter/ContentEditViewFilter.php
  lib/Content/View/Provider/Configured.php
Labels: enhancement

#219 EZP-28930: Labels are one line below checkbox/radiobutton
  bundle/Resources/views/ContentType/field_types.html.twig
Labels: bug

#223 EZP-28944: ISE 500 when deleting Draft
  bundle/Controller/ContentEditController.php
  bundle/Resources/views/http/302_empty_content.html.twig
  lib/Content/View/Builder/ContentCreateViewBuilder.php
  lib/Content/View/Builder/ContentEditViewBuilder.php
  lib/Content/View/ContentCreateSuccessView.php
  lib/Content/View/ContentEditSuccessView.php
Labels: QA done, bug, ready for review

#225 Revert "EZP-28930: Labels are one line below checkbox/radiobutton"
  bundle/Resources/views/ContentType/field_types.html.twig
Labels: bug

#224 EZP-28902: Creating a user with existing username results in Internal Server Error.
  bundle/Resources/translations/validators.en.xlf
  lib/Validator/Constraints/FieldValueValidator.php
  lib/Validator/Constraints/FieldValueValidatorMessages.php
Labels: ready for QA, ready for review

#226 EZP-28279: User cannot set max file size in Image field type
  bundle/Resources/translations/ezrepoforms_content_type.en.xlf
  lib/FieldType/Mapper/ImageFormMapper.php
Labels: QA done

#227 EZP-28939: Internal Server Error when saving unpublished Draft
  lib/Content/View/Builder/ContentEditViewBuilder.php
  lib/Content/View/ContentEditView.php
  lib/Form/ActionDispatcher/ContentDispatcher.php
  lib/Form/Processor/ContentFormProcessor.php
Labels: bug, ready for QA

#228 EZP-29012: Invalid initial language code set after saving content draft
  lib/Data/Mapper/ContentUpdateMapper.php
Labels: QA done, bug
