Repository ezsystems/repository-forms, pull requests merged in 2019-07, with the labels that each got.

#300 EZP-30668: move core tests classes from AdminUI to BehatBundle
  behat_suites.yml
  lib/Behat/Context/PagelayoutContext.php
  lib/Behat/Context/UserRegistrationContext.php
Labels: Ready for MERGE

#302 EZP-30529: Injected Field Types into Repository from DI Container
  bundle/Resources/config/services.yaml
  lib/Form/Type/ContentType/FieldTypeChoiceType.php
Labels: Improvement, QA approved

#301 EZP-30712: Fixed reverseTransform for midnight value
  lib/FieldType/DataTransformer/TimeValueTransformer.php
  tests/RepositoryForms/FieldType/DataTransformer/TimeValueTransformerTest.php
Labels: Bug, QA approved
