Repository ezsystems/repository-forms, pull requests merged in 2019-01, with the labels that each got.

#272 Fixed declaration of LimitationValueRenderingExtensionTest::doIntegrationTest
  tests/RepositoryForms/Twig/LimitationValueRenderingExtensionTest.php
Labels: Improvement, Ready for review

#273 EZP-29849: Allow user to remove location in subtree limitation
  lib/Limitation/DataTransformer/UDWBasedValueModelTransformer.php
  lib/Limitation/DataTransformer/UDWBasedValueTransformer.php
  lib/Limitation/DataTransformer/UDWBasedValueViewTransformer.php
  lib/Limitation/Mapper/UDWBasedMapper.php
  tests/RepositoryForms/Limitation/DataTransformer/UDWBasedValueModelTransformerTest.php
  tests/RepositoryForms/Limitation/DataTransformer/UDWBasedValueViewTransformerTest.php
Labels: Feature, QA approved, Ready for review

#276 EZP-29857: Unable to upload audio to Media field type
  lib/FieldType/Mapper/MediaFormMapper.php
Labels: QA approved
