Repository ezsystems/repository-forms, pull requests merged in 2019-03, with the labels that each got.

#270 EZP-29979: As a developer I would like to use getLocation method on ContentCreateSuccessView and ContentEditSuccessView
  lib/Content/View/Builder/ContentCreateViewBuilder.php
  lib/Content/View/Builder/ContentEditViewBuilder.php
  lib/Content/View/ContentCreateSuccessView.php
  lib/Content/View/ContentEditSuccessView.php
Labels: Ready for QA

#282 EZP-30297: Error when I try to add a translation for a user object
  lib/Data/ContentTranslationData.php
  lib/FieldType/Mapper/UserAccountFieldValueFormMapper.php
  lib/Form/Type/Content/ContentEditType.php
Labels: QA approved, Ready for review

#286 EZP-30362: Hidden default location in Relation List field type crashes Content Type editing
  bundle/Resources/views/ContentType/field_types.html.twig
Labels: Ready for QA

#284 Fixed ez_policy_limitation translation extractor for no limitations case
  lib/Translation/LimitationTranslationExtractor.php
  tests/RepositoryForms/Translation/LimitationTranslationExtractorTest.php
  tests/RepositoryForms/Translation/fixtures/input_policies.yaml
Labels: Bug, Ready for QA
