Repository ezsystems/repository-forms, pull requests merged in 2019-12, with the labels that each got.

#322 EZP-31020: Revised UI labels and messages
  bundle/Resources/translations/ezrepoforms_content.en.xlf
  bundle/Resources/translations/ezrepoforms_content_type.en.xlf
  bundle/Resources/translations/ezrepoforms_fieldtype.en.xlf
  bundle/Resources/translations/ezrepoforms_role.en.xlf
  bundle/Resources/translations/ezrepoforms_user.en.xlf
  bundle/Resources/translations/messages.en.xlf
  bundle/Resources/translations/validators.en.xlf
  lib/Form/Type/FieldType/MediaFieldType.php
  lib/Translation/SortingTranslationExtractor.php
  lib/Validator/Constraints/FieldValueValidatorMessages.php
Labels: Ready for MERGE

#328 EZP-31021: Revised exception and command messages
  bundle/DependencyInjection/Compiler/FieldTypeFormMapperDispatcherPass.php
  bundle/DependencyInjection/Compiler/LimitationFormMapperPass.php
  bundle/DependencyInjection/Compiler/LimitationValueMapperPass.php
  lib/Behat/Context/ContentTypeContext.php
  lib/Behat/Context/PagelayoutContext.php
  lib/Behat/Context/SelectionFieldTypeFormContext.php
  lib/ConfigResolver/ConfigurableSudoRepositoryLoader.php
  lib/Content/View/Builder/ContentCreateViewBuilder.php
  lib/Content/View/Builder/ContentEditViewBuilder.php
  lib/FieldType/DataTransformer/AbstractBinaryBaseTransformer.php
  lib/FieldType/DataTransformer/DateTimeValueTransformer.php
  lib/FieldType/DataTransformer/DateValueTransformer.php
  lib/FieldType/DataTransformer/ImageAssetValueTransformer.php
  lib/FieldType/DataTransformer/TimeValueTransformer.php
  lib/Form/DataTransformer/DateIntervalToArrayTransformer.php
  lib/Form/Processor/ContentFormProcessor.php
  lib/Form/Processor/ContentTypeFormProcessor.php
  lib/Limitation/Mapper/ContentTypeLimitationMapper.php
  lib/Limitation/Mapper/LanguageLimitationMapper.php
  lib/Limitation/Mapper/ObjectStateLimitationMapper.php
  lib/Limitation/Mapper/SectionLimitationMapper.php
  lib/Limitation/Templating/LimitationBlockRenderer.php
  lib/User/ConfigurableSudoRepositoryLoader.php
  tests/RepositoryForms/Limitation/Mapper/ContentTypeLimitationMapperTest.php
  tests/RepositoryForms/Limitation/Mapper/LanguageTypeLimitationMapperTest.php
  tests/RepositoryForms/Limitation/Mapper/ObjectStateLimitationMapperTest.php
  tests/RepositoryForms/Limitation/Mapper/SectionLimitationMapperTest.php
Labels: Ready for MERGE

#330 EZP-31238: marked alternative image text as optional to ensure consistence with fieldtype
  lib/Form/Type/FieldType/ImageFieldType.php
Labels: Bug, QA approved

#325 EZP-28900: Removed view transformer from FloatFieldType
  lib/Form/Type/FieldType/FloatFieldType.php
Labels: Bug, QA approved, Ready for review
