Repository ezsystems/repository-forms, pull requests merged in 2019-08, with the labels that each got.

#307 EZP-30814: Removed Twig deprecations
  bundle/Resources/views/limitation_values.html.twig
Labels: Improvement

#304 EZP-30812: Fixed deprecated use of Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch method
  lib/Data/Mapper/ContentTypeDraftMapper.php
  lib/Form/ActionDispatcher/AbstractActionDispatcher.php
  tests/RepositoryForms/Data/Mapper/ContentTypeDraftMapperTest.php
Labels: Improvement, QA approved

#308 Fixed broken integration test for ez_render_field_definition_edit function
  tests/RepositoryForms/Twig/_fixtures/field_edit_rendering_functions/ez_render_field_definition_edit.test
Labels: Bug

#309 EZP-30828: Replaced \Symfony\Component\EventDispatcher\Event usage in favor of Symfony\Contracts\EventDispatcher\Event
  lib/Event/FieldDefinitionMappingEvent.php
Labels: Improvement, QA approved

#310 Adjusted tests for changes in templates path
  lib/Behat/Context/PagelayoutContext.php
Labels: Ready for MERGE

#313 EZP-30880: Aligned Matcher Factories services definitions with Kernel changes
  bundle/Resources/config/views.yaml
Labels: Improvement, QA approved
