Repository ezsystems/repository-forms, pull requests merged in 2019-05, with the labels that each got.

#287 EZP-30390: Removed deprecated ezpage field type
  bundle/Resources/config/fieldtypes.yml
  bundle/Resources/translations/ezrepoforms_content_type.en.xlf
  bundle/Resources/views/ContentType/field_types.html.twig
  lib/FieldType/Mapper/PageFormMapper.php
Labels: Improvement

#291 EZP-30315 [Travis] Standarize and clean up travis configurations across the repositories
  .travis.yml
Labels: Ready for review

#288 EZP-30417: Add notifications to the password reset view
  lib/Validator/Constraints/Password.php
  tests/RepositoryForms/Validator/Constraints/PasswordTest.php
  tests/RepositoryForms/Validator/Constraints/UserAccountPasswordTest.php
Labels: Bug, QA approved

#294 EZP-30586: Adding of Selection FieldType without configured options leads to an 500 error
  lib/Form/DataTransformer/MultilingualSelectionTransformer.php
Labels: Bug, QA approved
