Repository ezsystems/repository-forms, pull requests merged in 2019-06, with the labels that each got.

#290 EZP-30503: Change names of paramters
  bundle/Controller/UserController.php
  bundle/Resources/views/Content/content_create_draft.html.twig
  bundle/Resources/views/Content/content_edit.html.twig
  bundle/Resources/views/content_name/content_name.html.twig
  features/User/Registration/user_registration.feature
  lib/Content/View/Builder/ContentCreateViewBuilder.php
  lib/Content/View/Builder/ContentEditViewBuilder.php
Labels: Improvement, Ready for review

#297 EZP-30517: Dropped obsolete RichText FieldType services
  bundle/Resources/config/fieldtypes.yml
  lib/FieldType/DataTransformer/RichTextValueTransformer.php
  lib/FieldType/Mapper/RichTextFormMapper.php
  lib/Form/Type/FieldType/RichTextFieldType.php
Labels: Improvement, Ready for MERGE

#292 EZP-30462: Change `ez.fieldFormMapper` tag to `ezplatform.field_type.form_mapper`
  bundle/DependencyInjection/Compiler/FieldTypeFormMapperDispatcherPass.php
  bundle/Resources/config/fieldtypes.yaml
  tests/RepositoryFormsBundle/DependencyInjection/Compiler/FieldTypeFormMapperDispatcherPassTest.php
Labels: Feature, QA approved

#299 EZP-30627: Unified Twig helpers naming
  bundle/Resources/views/ContentType/field_definition_row.html.twig
  lib/Twig/FieldEditRenderingExtension.php
  tests/RepositoryForms/Twig/_fixtures/field_edit_rendering_functions/ez_render_fielddefinition_edit.test
Labels: Improvement, Ready for review
