Repository ezsystems/repository-forms, pull requests merged in 2019-09, with the labels that each got.

#314 EZP-30906: Removed deprecated templating component integration
  bundle/Resources/config/ezpublish_default_settings.yaml
  bundle/Resources/config/kernel.yaml
  bundle/Resources/config/role.yaml
Labels: QA approved

#311 EZP-30797: As an administrator, I want to configure a password expiration for users
  bundle/Resources/translations/ezrepoforms_content_type.en.xlf
  lib/FieldType/Mapper/UserAccountFieldValueFormMapper.php
Labels: Feature, QA approved

#315 EZP-30938: Removed usage of deprecated setCurrentUser method
  lib/Behat/Context/ContentTypeContext.php
  lib/Behat/Context/UserRegistrationContext.php
Labels: Improvement, Ready for MERGE

#317 EZP-30394: Re-implement User Field Type
  composer.json
  lib/Behat/Context/UserRegistrationContext.php
  lib/Form/EventSubscriber/UserFieldsSubscriber.php
  lib/Form/Processor/User/UserCreateFormProcessor.php
  lib/Form/Processor/User/UserUpdateFormProcessor.php
Labels: QA approved
