Repository ezsystems/repository-forms, pull requests merged in 2019-10, with the labels that each got.

#320 EZP-30988: Fixed typo in the user password expiration label
  bundle/Resources/translations/ezrepoforms_content_type.en.xlf
Labels: Bug

#319 EZP-30983: As an Administrator, I want prevent users from reusing old password
  bundle/Resources/translations/ezrepoforms_content_type.en.xlf
  lib/FieldType/Mapper/UserAccountFieldValueFormMapper.php
Labels: QA approved

#321 EZP-30985: Removed deprecated choices_as_values Symfony form option
  lib/FieldType/Mapper/AuthorFormMapper.php
  lib/FieldType/Mapper/CountryFormMapper.php
  lib/FieldType/Mapper/DateFormMapper.php
  lib/FieldType/Mapper/DateTimeFormMapper.php
  lib/FieldType/Mapper/MediaFormMapper.php
  lib/FieldType/Mapper/PageFormMapper.php
  lib/FieldType/Mapper/RelationFormMapper.php
  lib/FieldType/Mapper/RelationListFormMapper.php
  lib/FieldType/Mapper/TimeFormMapper.php
  lib/Form/Type/ContentType/FieldTypeChoiceType.php
  lib/Form/Type/ContentType/SortFieldChoiceType.php
  lib/Form/Type/ContentType/SortOrderChoiceType.php
  lib/Form/Type/FieldDefinition/FieldDefinitionType.php
  lib/Form/Type/FieldType/CountryFieldType.php
  lib/Form/Type/FieldType/SelectionFieldType.php
  lib/Form/Type/Role/PolicyType.php
  lib/Form/Type/URL/URLListType.php
  lib/Limitation/Mapper/MultipleSelectionBasedMapper.php
Labels: Improvement, QA approved, Ready for MERGE
