Repository ezsystems/repository-forms, pull requests merged in 2020-04, with the labels that each got.

#336 [Travis] Set Docker PHP image used for installing dependencies
  .travis.yml
Labels: Bug

#332 EZP-31317: Loaded ContentType using preferred language in UserController
  bundle/Controller/UserController.php
  bundle/Resources/config/services.yml
Labels: Bug, QA approved

#338 EZP-31449: Adapted TranslatablePropertyTransformer to properly handle nulls
  lib/Form/DataTransformer/TranslatablePropertyTransformer.php
  tests/RepositoryForms/Form/DataTransformer/TranslatablePropertyTransformerTest.php
Labels: Bug, QA approved

#340 EZP-31581: Added missing translation
  bundle/Resources/translations/validators.en.xlf
Labels: Bug, QA approved

#339 EZP-31542: Added PHP 7.4 support (eZ Platform 2.5)
  .travis.yml
  composer.json
  lib/FieldType/DataTransformer/SingleCountryValueTransformer.php
  phpunit.xml.dist
  tests/RepositoryForms/FieldType/DataTransformer/SingleCountryValueTransformerTest.php
Labels: Improvement, Ready for QA
